# This is a basic workflow to help you get started with Actions

name: UpdateFile

on:
  schedule:
    - cron: '0/5 * * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Hello, world! >> file.txt
          date >> file.txt
          
      - name: Commit and push changes
        run: |
          git config --global user.name "massyn"
          git config --global user.email "phil.massyn@icloud.com"

          git add -A
          git commit -m "commit message"
          git push
